[package]
name = "storage"
version = "0.1.0"
edition = "2021"

[dependencies]
types = { path = "../types" }
thiserror = "1"
sled = "0.34"
tempfile = "3"
metrics = { path = "../metrics" }

[dev-dependencies]
proptest = "1"

[dependencies.bincode]
version = "1"
