[package]
name = "consensus"
version = "0.1.0"
edition = "2021"

[dependencies]
types = { path = "../types" }
mempool = { path = "../mempool" }
storage = { path = "../storage" }
thiserror = "1"
metrics = { path = "../metrics" }
